name: run_tests-Release

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cmake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: make
        run: cd build && make
      - name: Run tests
        run: /home/runner/work/cpp-redis-clone/cpp-redis-clone/build/tests/redis_test