name: run_tests-Debug

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: cmake
        run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Werror" ..
      - name: make
        run: cd build && make
      - name: Run Test
        run: /home/runner/work/run_tests/run_tests/build/test/redis_test